config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    registrations: "admin/registrations",
    sessions: "admin/sessions"
  }

  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post 'guest_login' => 'public/sessions#guest_login'
  end


  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'

    resource :user, only: [:show, :edit, :update, :index]
    resources :shops do
      collection do
        get 'search'
      end
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shop.rb
class Shop < ApplicationRecord
  geocoded_by :address
  after_validation :geocode

  belongs_to :user

  validates :name, presence: true
  validates :introduction, presence: true
  validates :address, presence: true
  validates :star, presence: true

  acts_as_taggable_on :tags

  def self.ransackable_attributes(auth_object = nil)
    ["address", "created_at", "id", "introduction", "latitude", "longitude", "name", "star", "updated_at", "user_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["user"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  has_many :shops, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true

  def self.guest
    find_or_create_by!(email: ENV['GUEST_USER_EMAIL']) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.last_name = 'Guest'
      user.first_name = 'User'
    end
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_fill: [width,height]).processed
  end
end

app/controllers/admin/users/confirmations_controller.rb
# frozen_string_literal: true

class Admin::Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Admin::Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/admin/users/passwords_controller.rb
# frozen_string_literal: true

class Admin::Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/users/registrations_controller.rb
# frozen_string_literal: true

class Admin::Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users/sessions_controller.rb
# frozen_string_literal: true

class Admin::Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/users/unlocks_controller.rb
# frozen_string_literal: true

class Admin::Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h5>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h5>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="container pt-5 pb-4">
  <div class="row justify-content-around">
    <div>
      Copyright©︎ Oshima Taishu
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="mt-3">
      <h2>
        <%= link_to root_path, class:"logo", id:"icon" do %>
         <i class="fas fa-utensils fa-flip"></i> Foodie <i class="fas fa-utensils fa-flip"></i>
        <% end %>
      </h2>
    </div>
  </div>

  <div class="row mt-3">
      <nav class="col-12 justify-content-center navbar navbar-expand-lg navbar-light">
        <ul class="d-flex">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to root_path, class:"header-btn" do %>
                <i class="fas fa-home"></i> Top
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to user_path(current_user.id), class:"header-btn" do %>
                <i class="fas fa-circle-user"></i> Mypage
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to shops_path, class:"header-btn" do %>
                <i class="fas fa-shop"></i> Shops
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_shop_path, class:"header-btn" do %>
                <i class="fas fa-plus"></i> New Shop
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class:"header-btn" do %>
                <i class="fas fa-right-from-bracket"></i> Log out
              <% end %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to new_user_session_path, class:"header-btn" do %>
                <i class="fas fa-home"></i> Log in
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class:"header-btn" do %>
                <i class="fas fa-home"></i> Sign up
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to guest_login_path, method: :post, class:"header-btn" do %>
                <i class="fas fa-home"></i> Guest Login
              <% end %>
            </li>
          <% end %>
        </ul>
      </nav>
  </div>
  <div class="row mt-1">
    <div class>
      <%= link_to "https://www.google.com/maps?authuser=0", target: :blank, rel: "noopener noreferrer" do %>Google Mapへ<% end %>
    </div>
  </div>


  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodie</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= include_gon %>
    <script src="https://kit.fontawesome.com/da841da865.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body>
    <header>
      <%= render 'layouts/header.html.erb' %>
    </header>
    <main class="mx-auto mt-2 col-md-12">
      <%= yield %>
    </main>

    <footer>
      <%= render 'layouts/footer.html.erb' %>
    </footer>
  </body>
</html>